server:
  port: 8072

spring:
  application:
    name: "gateway-server"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gateway-server"
    description: "KukeBoard Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      kukeboard:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        registerHealthIndicator: true
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException

      critical:  # 중요 서비스용
        slidingWindowSize: 20
        failureRateThreshold: 30
        waitDurationInOpenState: 20s
        slowCallDurationThreshold: 5s
        slowCallRateThreshold: 50

    instances:
      articlesCircuitBreaker:
        baseConfig: default
      articleLikesCircuitBreaker:
        baseConfig: critical  # 좋아요는 중요도가 높음
      articleViewsCircuitBreaker:
        baseConfig: default
        waitDurationInOpenState: 5s  # 조회수는 빠른 복구

  timelimiter:
    configs:
      default:
        timeoutDuration: 10s
    instances:
      articlesCircuitBreaker:
        baseConfig: default
      articleLikesCircuitBreaker:
        timeoutDuration: 5s  # 좋아요는 빠른 응답 필요

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://kukeboard:root@localhost:8070/eureka/

