spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb_spring?useSSL=false
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

# App Properties
bezkoder:
  app:
    jwtSecret: '======================BezKoder=Spring==========================='
    jwtExpirationMs: 86400000